let courses = [];
let course1 = prompt("Enter first course name.")
let course2 = prompt("Enter second course name.")
let course3 = prompt("Enter third course name.")
let course4 = prompt("Enter fourth course name.")
let course5 = prompt("Enter fivth course name.")
courses.push(course1,course2,course3,course4,course5)
alert(`Your list is here:\n ${courses}`)
let update_course1 = prompt("Edit course 1:",`${course1}`)
let update_course2 = prompt("Edit course 2:",`${course2}`)
let update_course3 = prompt("Edit course 3:",`${course3}`)
let update_course4 = prompt("Edit course 4:",`${course4}`)
let update_course5 = prompt("Edit course 5:",`${course5}`)
// console.log(courses)
courses.splice(0,1,update_course1)
courses.splice(1,1,update_course2)
courses.splice(2,1,update_course3)
courses.splice(3,1,update_course4)
courses.splice(4,1,update_course5)
alert(`Your Updated list is here:\n${courses.join(",")}`)